### PR TITLE
Get -r automatically if in .git folder. Closes #9

### LINKED ISSUE #9: Get the repo/branch from .git folder when run from within a repo

### PR DESCRIPTION
**Pull request by benjaminparnell**
@IamSmith would you mind taking a look?
/cc @matthojo

### CODE REVIEW

**Comment by matthojo** [comment]
:+1: looks good

**Comment by oliverjohnstone** [comment]
👍

**Comment by benjaminparnell** [comment]
@oliverjohnstone knew I'd get someone commenting

**Comment by oliverjohnstone** [comment]
@benjaminparnell I think this beats my longest open PR 😛

**Comment by matthojo** [comment]
It's alive!!!

Do you want me to PR https://github.com/matthojo/qa-report? We got ES6 and Promises...

**Comment by balaclark** [comment]
bitmoji

**Comment by microadam** [comment]
bitmoji

**Comment by benjaminparnell** [comment]
🙃

**Pull request closed without merging**
